---
abstract: 'Perl Authentication and Authorization via cookies'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires: {}
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300032, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache-AuthCookie
requires:
  Apache::Test: 1.35
  CGI: 3.12
  Class::Load: 0.03
  autobox: 1.10
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Apache-AuthCookie
  homepage: http://search.cpan.org/dist/Apache-AuthCookie/
  repository: git://github.com/mschout/apache-authcookie.git
version: 3.20
